### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by wangsha** [tryagainconcepts/pancake#1]
Here are some of the scenarios, please check we cover them:
- [x] task schedule integration (alert only activate for on-shift users, similar to scheduled maintenance)
- [x] acknowledgement (unscheduled maintenance)
- [x] able to calculate *uptime* metrics

**Comment by blurrcat** [comment]
1. Middle can create subscriptions according to a user's work schedule.
2. I'll add an Acknowledgement model
3. This is dependent on how events are sent to pancake. If all events are sent timely to it, uptime can be calculated.

**Comment by blurrcat** [comment]
Added Acknowledgement in eaf229d0faef1d065e09b7c76bf79170fff7fa88
